### ISSUE TITLE
Not all teamfolders are listed on "tbx.exe teamfolder member list"

### ISSUE THREAD

**Issue by vkdnl** [watermint/toolbox#596] opened 2022-04-30 10:45 UTC
When we run the command "tbx.exe teamfolder list" then we see (as expected) all the team folders.
But when we run the command "tbx.exe teamfolder member list" then we only see some team folders
All the dropbox business teamfolders have members, so we do not understand why the list is partial.
Are we doing something wrong?

**Comment by watermint** [comment] 2022-05-01 02:05
Interesting. Which version of tbx.exe did you used?

**Comment by vkdnl** [comment] 2022-05-01 07:10
I used the latest version: 102.8.1164

**Comment by vkdnl** [comment] 2022-05-09 11:24
@Takayuki Okazaki (watermint): can i get in contact with you to see if you can solve the issue? I like to use your program, but i cannot use it at this moment.

**Comment by watermint** [comment] 2022-08-15 04:01
Hey @vkdnl , sorry for delayed response.
Your team seems like a type of team space (not team folder). The command `teamfolder list` returns only one folder if your team has team space. Unfortunately, there is no direct alternative commands for team space admins. I'm planning to expand support for team space team users in the future (no timeline yet). Please see progress in #624.

Detail: https://github.com/watermint/toolbox/discussions/633
I'll close this issue as duplicate of #624. Thanks.

**Closed by watermint** 2022-08-15 04:01 UTC
Labels: duplicate, question
